### ISSUE TITLE
Doesn't install on OS X 10.9

### ISSUE THREAD

**Issue by dbonadiman** [vchahun/pyfst#18]
While installing pyfst on osx 10.9 mavericks I get a lot of error like

```
/usr/local/include/fst/pair-weight.h:120:14: error: call to 'isspace' is ambiguous
        } while (isspace(c)); 
```

 and i'm not able to install the package.

**Comment by dbonadiman** [comment]
a simple solution was to replace all occurrences of  isspace with std::isspace in the header of openfst in /usr/local/include/fst/

**Comment by kylebgorman** [comment]
This worked for me with OS X 10.9 and OpenFST 1.4.1, but perhaps produced another problem. For instance, if I try to read a symbols table, it churns for about 30 seconds then returns 

```
ERROR: SymbolTable::Read: read failed
```

and segfaults. I know the symbol table is fine (it is just the printable ascii chars) because it works with `fstcompile` (etc.).

Is pyfst still being maintained at all?

**Comment by stevenbedrick** [comment]
Regarding the symbol table issue- I was able to work around it by using binary symbol tables rather than ascii symbol tables. Now, I couldn't figure out how to _create_ a binary symbol table, and ultimately ended up writing a little C++ program to take care of it.

https://gist.github.com/stevenbedrick/3cd157b16536a544bb9b

Once they'd been converted to the binary serialization format, PyFST's symbol table IO functions worked as expected.

**Comment by vchahun** [comment]
@dbonadiman Seems like an issue between OpenFst and your compiler
@kylebgorman Symbol tables have to be binary, not text files
@stevenbedrick You could do:

``` python
sym = fst.SymbolTable()
sym['a']
print sym
```

(this will create a symbol table with 0=\epsilon, 1=a)

**Comment by stevenbedrick** [comment]
Thanks for the tip, Victor- very handy. However, it only solves the problem of creating a de novo symbol table. If you need to work with somebody else's ASCII symbol table (a very common use case, in our experience), you're still SOL when using PyFST (hence little binary conversion utility). How hard would it be to add support for `fst::SymbolTable::ReadText()`?

**Comment by kylebgorman** [comment]
Thanks Victor, that clarifies it for me.

+1 for @stevebedrick's experience...I didn't even realize that binary symbol tables existed in OpenFST.
